spring:
  application:
    name: chain-store
  data:
    mongodb:
      uri: mongodb://localhost:27017/chain-store
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

kafka:
  topics:
    phone-inventory-get: phone-inventory-get
    phone-inventory-update: phone-inventory-update
    phone-inventory-delete: phone-inventory-delete
server:
  port: 8081
logging:
  level:
    com.amdocs.chainstore: DEBUG
    org.springframework.data.mongodb: DEBUG