
openapi: 3.0.0
info:
  title: Chain Store Microservice
  version: 1.0.0
  description: API for managing chain store branches

paths:
  /store/createStore:
    post:
      summary: Create a new store
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StoreCreateRequest'
      responses:
        '201':
          description: Store created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Store'
        '400':
          description: Bad request
        '422':
          description: Validation error
        '500':
          description: Internal server error

  /store/{id}:
    get:
      summary: Get store details
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Store details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Store'
        '400':
          description: Bad request
        '404':
          description: Store not found
        '500':
          description: Internal server error

    delete:
      summary: Delete a store
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Store deleted successfully
        '400':
          description: Bad request
        '404':
          description: Store not found
        '500':
          description: Internal server error

  /store/updateStore:
    put:
      summary: Update store details
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StoreUpdateRequest'
      responses:
        '200':
          description: Store updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Store'
        '400':
          description: Bad request
        '404':
          description: Store not found
        '422':
          description: Validation error
        '500':
          description: Internal server error

components:
  schemas:
    Store:
      type: object
      properties:
        id:
          type: string
        storeName:
          type: string
          minLength: 10
          maxLength: 50
        address:
          type: string
          minLength: 10
          maxLength: 50
        managerName:
          type: string
          minLength: 5
          maxLength: 15

    StoreCreateRequest:
      type: object
      required:
        - storeName
        - address
        - managerName
      properties:
        storeName:
          type: string
          minLength: 10
          maxLength: 50
        address:
          type: string
          minLength: 10
          maxLength: 50
        managerName:
          type: string
          minLength: 5
          maxLength: 15

    StoreUpdateRequest:
      type: object
      required:
        - id
        - storeName
        - address
        - managerName
      properties:
        id:
          type: string
        storeName:
          type: string
          minLength: 10
          maxLength: 50
        address:
          type: string
          minLength: 10
          maxLength: 50
        managerName:
          type: string
          minLength: 5
          maxLength: 15
