spring:
  application:
    name: phone-store
  data:
    mongodb:
      uri: mongodb://localhost:27017/phone-store
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: phone-store-group
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      enable-auto-commit: true
      auto-commit-interval: 1000
      session-timeout-ms: 30000
      max-poll-records: 500

logging:
  level:
    com.phonestore: DEBUG
    org.springframework.data.mongodb: DEBUG
    org.springframework.kafka: DEBUG
    org.apache.kafka: INFO

server:
  port: 8080

# Kafka topics configuration
kafka-topics:
  phone-inventory-get: phone-inventory-get
  phone-inventory-update: phone-inventory-update
  phone-inventory-delete: phone-inventory-delete
